import { Sometype_Mono } from "next/font/google";
import "./reset.css";
import "./globals.css";
import Header from "./components/Header";

const sometype = Sometype_Mono({ subsets: ["latin"] });
// const plex_sans = IBM_Plex_Sans({ subsets: ["latin"] });


export const metadata = {
    title: "Manh Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={sometype.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
