import { Sometype_Mono } from "next/font/google";
import "./reset.css";
import "./globals.css";
import Header from "./components/Header";
import Stage from "./components/three/stage";
// const sometype = Sometype_Mono({ subsets: ["latin"] });
// const plex_sans = IBM_Plex_Sans({ subsets: ["latin"] });
import { Sometype, plex_sans } from "./fonts";
import Footer from "./components/Footer";

export const metadata = {
    title: "Manh Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${Sometype.variable} ${plex_sans.variable}`}>
            <body>
                <Header />
                {children}
                <Footer />
                <div className="bg-three">
                    {/* <Stage /> */}
                </div>
            </body>
        </html>
    );
}
